const assert=require('assert');
const fs=require('fs');
const path=require('path');
const Merge=require('../runtime/legacy-hardening-merge.js');
const overlay=JSON.parse(fs.readFileSync(path.join(__dirname,'../data/legacy-route-hardening-overlay-batch2.v0.37.json'),'utf8'));
const repl=JSON.parse(fs.readFileSync(path.join(__dirname,'../data/replacement-route-packs-batch2.v0.37.json'),'utf8'));
assert.strictEqual(overlay.routes.length,5);
assert.strictEqual(repl.routes.length,4);
assert.strictEqual(repl.routes.filter(x=>x.vehicleFit.level==='V1').length,2);
const r6=overlay.routes.find(x=>x.legacyRouteId==='R006');
assert.strictEqual(Merge.routeGate({vehicle:{widthM:2.0},nowLocalHHMM:'20:00',weather:'clear'},r6,'preview'),'DESTINATION_WIDTH_REJECT');
const r9=overlay.routes.find(x=>x.legacyRouteId==='R009');
assert.strictEqual(Merge.routeGate({vehicle:{widthM:1.8},nowLocalHHMM:'19:01',weather:'clear'},r9,'preview'),'FULL_ROUTE_TOO_LATE');
const r10=overlay.routes.find(x=>x.legacyRouteId==='R010');
assert.strictEqual(Merge.routeGate({vehicle:{widthM:1.8},nowLocalHHMM:'17:16',weather:'clear'},r10,'preview'),'FULL_ROUTE_TOO_LATE');
assert.strictEqual(r9.timeRules.correctedFullRouteLatestRecommendedDeparture,'19:00');
assert.strictEqual(r10.timeRules.recommendedRoundedTime,'17:15');
assert.strictEqual(repl.routes.find(x=>x.routePackId==='SAFE_YOKOHAMA_BRIDGES_KARENA_01').vehicleFit.maxWidthM,2.3);
console.log(JSON.stringify({passed:true,audited:5,v1Replacements:2,previewReplacements:2},null,2));